version: "3.9"

services:
  # Имидж сервиса вэб приложения собранный из докен-файла
  web:
    build: .
    ports:
      - "5000:5000"

  # Имидж сервиса Redis взятый готовым из риджестри
  redis:
    image: "redis:alpine"
